### PR TITLE
doi changes

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Comment by jukent** [comment]
@droumis it would be great if you could comment your ORCID here or add it to the `CITATION.cff` file yourself.

The links in the Zenodo badges will fail until the first release is made.

**Comment by droumis** [comment]
Here you go!

0000-0003-4670-1657

**Comment by droumis** [comment]
looks great, thanks @jukent !

**Comment by jukent** [comment]
Great released and on Zenodo!

**Pull request merged**
